//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDePermisos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        public CUENTA()
        {
            this.EMPLEADO = new HashSet<EMPLEADO>();
        }
    
        public decimal IDCUENTA { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public Nullable<decimal> IDPERFILCUENTA { get; set; }
        public Nullable<decimal> IDESTADO { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual PERFILCUENTA PERFILCUENTA { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
    }
}
