//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDePermisos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public string RUT { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOPATERNO { get; set; }
        public string APELLIDOMATERNO { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHACONTRATACION { get; set; }
        public Nullable<decimal> IDESTADO { get; set; }
        public Nullable<decimal> IDCARGO { get; set; }
        public Nullable<decimal> IDCOMUNA { get; set; }
        public Nullable<decimal> IDDEPARTAMENTO { get; set; }
        public Nullable<decimal> IDCUENTA { get; set; }
        public Nullable<decimal> IDTIPOCONTRATO { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual CUENTA CUENTA { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual TIPOCONTRATO TIPOCONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
