//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDePermisos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO
    {
        public ESTADO()
        {
            this.CUENTA = new HashSet<CUENTA>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
            this.UNIDAD = new HashSet<UNIDAD>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
            this.TIPOPERMISO = new HashSet<TIPOPERMISO>();
        }
    
        public decimal IDESTADO { get; set; }
        public string NOMBREESTADO { get; set; }
        public string TIPO { get; set; }
    
        public virtual ICollection<CUENTA> CUENTA { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        public virtual ICollection<UNIDAD> UNIDAD { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
        public virtual ICollection<TIPOPERMISO> TIPOPERMISO { get; set; }
    }
}
