//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDePermisos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFILCUENTA
    {
        public PERFILCUENTA()
        {
            this.CUENTA = new HashSet<CUENTA>();
        }
    
        public decimal IDPERFILCUENTA { get; set; }
        public string NOMBREPERFILCUENTA { get; set; }
    
        public virtual ICollection<CUENTA> CUENTA { get; set; }
    }
}
