//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDePermisos.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<CUENTA> CUENTA { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<ESTADO> ESTADO { get; set; }
        public DbSet<MOTIVO> MOTIVO { get; set; }
        public DbSet<MUNICIPALIDAD> MUNICIPALIDAD { get; set; }
        public DbSet<PERFILCUENTA> PERFILCUENTA { get; set; }
        public DbSet<PROVINCIA> PROVINCIA { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<SOLICITUD> SOLICITUD { get; set; }
        public DbSet<TIPOCONTRATO> TIPOCONTRATO { get; set; }
        public DbSet<TIPOPERMISO> TIPOPERMISO { get; set; }
        public DbSet<UNIDAD> UNIDAD { get; set; }
    }
}
