//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDePermisos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public decimal IDSOLICITUD { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHASOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHATERMINO { get; set; }
        public Nullable<decimal> IDTIPOPERMISO { get; set; }
        public Nullable<decimal> RUT { get; set; }
        public Nullable<decimal> AUTORIZADOR { get; set; }
        public Nullable<decimal> IDESTADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual TIPOPERMISO TIPOPERMISO { get; set; }
    }
}
