//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDePermisos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOCONTRATO
    {
        public TIPOCONTRATO()
        {
            this.EMPLEADO = new HashSet<EMPLEADO>();
        }
    
        public decimal IDTIPOCONTRATO { get; set; }
        public string NOMBRETIPOCONTRATO { get; set; }
    
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
    }
}
